import type { Metadata } from 'next'

import { Noto_Sans_JP } from 'next/font/google'

import '@/assets/styles/globals.css'
import { Toaster } from '@/components/ui/toaster'
import { LoadingProvider } from '@/hooks/use-loading'

const notoSansJP = Noto_Sans_JP({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-noto-sans-jp',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ja' className={`${notoSansJP.variable}`}>
      <body className={`font-sans antialiased`}>
        <LoadingProvider>
          {children}
          <Toaster />
        </LoadingProvider>
      </body>
    </html>
  )
}
