import type { Metadata } from 'next'

import '@/assets/styles/globals.css'
import { Toaster } from '@/components/ui/toaster'
import { LoadingProvider } from '@/hooks/use-loading'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className='antialiased'>
        <LoadingProvider>
          {children}
          <Toaster />
        </LoadingProvider>
      </body>
    </html>
  )
}
